@csrf
<div class="admin-form-grid">
    <div class="form-card"><div class="form-card-header"><div class="form-card-icon"><i class="fas fa-star"></i></div><div><p class="form-card-title">Parent Trust Card</p><p class="form-card-subtitle">Title, description, icons and footer text</p></div></div><div class="form-card-body">
        <div class="field-group"><label class="field-label" for="title">Title <span class="req">*</span></label><div class="input-icon-wrap"><i class="fas fa-heading icon"></i><input type="text" name="title" id="title" value="{{ old('title', $card->title ?? '') }}" required class="field-input {{ $errors->has('title') ? 'error' : '' }}"></div>@if($errors->has('title'))<p class="field-error"><i class="fas fa-exclamation-circle"></i>{{ $errors->first('title') }}</p>@endif</div>
        <div class="field-group"><label class="field-label" for="description">Description</label><textarea name="description" id="description" rows="5" class="field-input">{{ old('description', $card->description ?? '') }}</textarea></div>
        <div class="field-group"><label class="field-label" for="footer_text">Footer Text</label><textarea name="footer_text" id="footer_text" rows="3" class="field-input">{{ old('footer_text', $card->footer_text ?? '') }}</textarea><p class="field-hint"><i class="fas fa-info-circle"></i>Use &lt;strong&gt; and &lt;b&gt;&lt;/b&gt; if needed.</p></div>
        <div class="field-group"><label class="field-label" for="icon">Main Icon</label><div class="input-icon-wrap"><i class="fas fa-icons icon"></i><input type="text" name="icon" id="icon" value="{{ old('icon', $card->icon ?? '') }}" placeholder="bi bi-person-video3" class="field-input"></div></div>
        <div class="field-group"><label class="field-label" for="footer_icon">Footer Icon</label><div class="input-icon-wrap"><i class="fas fa-icons icon"></i><input type="text" name="footer_icon" id="footer_icon" value="{{ old('footer_icon', $card->footer_icon ?? '') }}" placeholder="bi bi-person-check" class="field-input"></div></div>
    </div></div>
    <div class="form-card"><div class="form-card-header"><div class="form-card-icon"><i class="fas fa-sliders-h"></i></div><div><p class="form-card-title">Display Settings</p><p class="form-card-subtitle">Color, order and status</p></div></div><div class="form-card-body">
        <div class="field-group"><label class="field-label" for="color_class">Color Class</label><div class="input-icon-wrap"><i class="fas fa-palette icon"></i><input type="text" name="color_class" id="color_class" value="{{ old('color_class', $card->color_class ?? '') }}" placeholder="kpt-card-red" class="field-input"></div></div>
        <div class="field-group"><label class="field-label" for="sort_order">Sort Order</label><div class="input-icon-wrap"><i class="fas fa-sort-numeric-down icon"></i><input type="number" name="sort_order" id="sort_order" value="{{ old('sort_order', $card->sort_order ?? 0) }}" min="0" class="field-input"></div></div>
        <div class="checkbox-grid"><label class="role-checkbox-item {{ old('status', $card->status ?? true) ? 'checked' : '' }}"><input type="checkbox" name="status" value="1" class="role-checkbox" {{ old('status', $card->status ?? true) ? 'checked' : '' }}><div class="check-icon"></div><span class="checkbox-text">Publish this card</span></label></div>
    </div></div>
</div>
<div class="form-actions mt-4"><button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> Save Card</button></div>